import {
  Component,
  OnInit,
  OnDestroy,
  signal,
  computed,
  inject,
  PLATFORM_ID,
} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import * as QRCode from 'qrcode';
import { BakongService, Product, GenerateQRResponse } from '../../services/bakong.service';

interface CartItem {
  product: Product;
  quantity: number;
}

type PageState = 'shop' | 'qr' | 'success' | 'expired';

@Component({
  selector: 'app-bakong-payment',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './bakong-payment.component.html',
  styleUrl: './bakong-payment.component.css',
})
export class BakongPaymentComponent implements OnInit, OnDestroy {
  private bakongService = inject(BakongService);
  private platformId = inject(PLATFORM_ID);

  // ── State ────────────────────────────────────────────────────
  pageState   = signal<PageState>('shop');
  products    = signal<Product[]>([]);
  cart        = signal<CartItem[]>([]);
  loading     = signal(false);
  error       = signal('');
  currency    = signal<'usd' | 'khr'>('usd');

  qrData      = signal<GenerateQRResponse | null>(null);
  qrDataUrl   = signal('');           // ← base64 PNG generated by qrcode library
  pollStatus  = signal<'idle' | 'polling' | 'paid' | 'expired'>('idle');
  pollMessage = signal('Waiting for payment…');
  saleResult  = signal<any>(null);
  secondsLeft = signal(900);

  private pollInterval: any;
  private countdownInterval: any;

  // ── Computed ─────────────────────────────────────────────────
  total = computed(() =>
    this.cart().reduce((sum: number, i: CartItem) => sum + i.product.unit_price * i.quantity, 0)
  );

  totalDisplay = computed(() => {
    const t = this.total();
    if (this.currency() === 'usd') return `$${t.toFixed(2)}`;
    return `${Math.round(t * 4100).toLocaleString()} ៛`;
  });

  cartCount = computed(() =>
    this.cart().reduce((s: number, i: CartItem) => s + i.quantity, 0)
  );

  countdown = computed(() => {
    const m = Math.floor(this.secondsLeft() / 60).toString().padStart(2, '0');
    const s = (this.secondsLeft() % 60).toString().padStart(2, '0');
    return `${m}:${s}`;
  });

  readonly TEST_USER_ID = '000000000000000000000001';

  ngOnInit() { this.loadProducts(); }
  ngOnDestroy() { this.stopPolling(); }

  // ── Products ─────────────────────────────────────────────────
  loadProducts() {
    this.loading.set(true);
    this.error.set('');
    this.bakongService.getProducts().subscribe({
      next: (res: any) => { this.products.set(res.data ?? []); this.loading.set(false); },
      error: () => {
        this.error.set('Could not load products. Is the backend running on port 4001?');
        this.loading.set(false);
      },
    });
  }

  // ── Cart ─────────────────────────────────────────────────────
  addToCart(product: Product) {
    const existing = this.cart().find((i: CartItem) => i.product._id === product._id);
    if (existing) {
      if (existing.quantity >= product.quantity_in_stock) return;
      this.cart.update((c: CartItem[]) =>
        c.map((i: CartItem) =>
          i.product._id === product._id ? { ...i, quantity: i.quantity + 1 } : i
        )
      );
    } else {
      this.cart.update((c: CartItem[]) => [...c, { product, quantity: 1 }]);
    }
  }

  removeFromCart(productId: string) {
    this.cart.update((c: CartItem[]) => c.filter((i: CartItem) => i.product._id !== productId));
  }

  changeQty(productId: string, delta: number) {
    this.cart.update((c: CartItem[]) =>
      c
        .map((i: CartItem) => {
          if (i.product._id !== productId) return i;
          const newQty = i.quantity + delta;
          return newQty <= 0
            ? null
            : { ...i, quantity: Math.min(newQty, i.product.quantity_in_stock) };
        })
        .filter(Boolean) as CartItem[]
    );
  }

  getCartItem(productId: string): CartItem | undefined {
    return this.cart().find((i: CartItem) => i.product._id === productId);
  }

  // ── Generate QR ───────────────────────────────────────────────
  generateQR() {
    if (this.cart().length === 0) return;
    this.loading.set(true);
    this.error.set('');

    const payload = {
      userId: this.TEST_USER_ID,
      currency: this.currency(),
      items: this.cart().map((i: CartItem) => ({
        product_id: i.product._id,
        quantity: i.quantity,
      })),
      notes: 'Bakong QR test order',
    };

    this.bakongService.generateQR(payload).subscribe({
      next: (res: GenerateQRResponse) => {
        this.qrData.set(res);
        this.secondsLeft.set(900);

        // Generate QR as base64 PNG — works in browser and SSR
        if (isPlatformBrowser(this.platformId)) {
          QRCode.toDataURL(res.qrString, {
            width: 280,
            margin: 2,
            color: { dark: '#000000', light: '#ffffff' },
            errorCorrectionLevel: 'M',
          })
            .then((dataUrl: string) => {
              this.qrDataUrl.set(dataUrl);
            })
            .catch((err: any) => {
              console.error('[QR] toDataURL error:', err);
              this.error.set('Failed to render QR image.');
            });
        }

        this.pageState.set('qr');
        this.loading.set(false);
        this.startPolling(res.sessionId);
        this.startCountdown();
      },
      error: (err: any) => {
        this.error.set(err?.error?.message ?? 'QR generation failed. Check the console.');
        this.loading.set(false);
      },
    });
  }

  // ── Polling ───────────────────────────────────────────────────
  private startPolling(sessionId: string) {
    this.pollStatus.set('polling');
    this.pollMessage.set('Waiting for payment…');

    this.pollInterval = setInterval(() => {
      this.bakongService.checkPayment(sessionId).subscribe({
        next: (res: any) => {
          if (res.isPaid) {
            this.saleResult.set(res.sale);
            this.pollStatus.set('paid');
            this.pollMessage.set('Payment confirmed! 🎉');
            this.stopPolling();
            setTimeout(() => this.pageState.set('success'), 800);
          } else if (res.message?.includes('expired')) {
            this.pollStatus.set('expired');
            this.pollMessage.set('QR expired.');
            this.stopPolling();
            this.pageState.set('expired');
          }
        },
        error: () => { /* silently retry */ },
      });
    }, 3000);
  }

  private stopPolling() {
    clearInterval(this.pollInterval);
    clearInterval(this.countdownInterval);
  }

  private startCountdown() {
    this.countdownInterval = setInterval(() => {
      this.secondsLeft.update((s: number) => {
        if (s <= 1) {
          this.stopPolling();
          if (this.pageState() === 'qr') this.pageState.set('expired');
          return 0;
        }
        return s - 1;
      });
    }, 1000);
  }

  // ── Navigation ────────────────────────────────────────────────
  startOver() {
    this.stopPolling();
    this.cart.set([]);
    this.qrData.set(null);
    this.qrDataUrl.set('');
    this.pollStatus.set('idle');
    this.saleResult.set(null);
    this.error.set('');
    this.pageState.set('shop');
    this.loadProducts();
  }
}
